require("TKLeone.remap")
require("TKLeone.config")
require("TKLeone.Treesitter")
require("TKLeone.nvimcmp")
require("TKLeone.indent-blankline")
require("TKLeone.sourcegraph")
require("TKLeone.colorscheme")
require("TKLeone.autoclose")
